import { FeaturedProductsSettings, HomepageHero, HomepageSection, HomepageSettings, HomepageTheme, NavbarSettings, PromoBanners } from './types';

export const DEFAULT_FEATURED_PRODUCTS_SETTINGS: FeaturedProductsSettings = {
  enabled: true,
  product_ids: [],
};

export const DEFAULT_NAVBAR_SETTINGS: NavbarSettings = {
  logo_url: '/D\'VERO.logo.png',
  desktop_menu_items: [
    { id: '1', label: 'Shirts', url: '/category/shirts' },
    { id: '2', label: 'Trousers', url: '/category/trousers' },
    { id: '3', label: 'About', url: '/about' },
  ],
  mobile_menu_items: [
    { id: '1', label: 'Shirts', url: '/category/shirts' },
    { id: '2', label: 'Trousers', url: '/category/trousers' },
    { id: '3', label: 'About Us', url: '/about' },
    { id: '4', label: 'Contact', url: '/contact' },
  ],
  announcement_bar_enabled: false,
  announcement_text: 'Complimentary shipping on orders above ₹2,999',
  transparent_navbar: true,
  sticky_navbar: true,
};

export const DEFAULT_HOMEPAGE_SETTINGS: HomepageSettings = {
  hero_height_desktop: '90vh',
  hero_height_mobile: '100dvh',
  products_per_row_desktop: 4,
  products_per_row_tablet: 2,
  products_per_row_mobile: 1,
  enable_newsletter: true,
  enable_footer: true,
  show_featured_products: true,
};

export const DEFAULT_HOMEPAGE_HERO: HomepageHero = {
  enabled: true,
  layout: 'split',
  label: 'POWER IN SIMPLICITY',
  heading: 'TIMELESS FORMALS',
  description: 'MODERN FITS. PREMIUM FABRICS. MADE FOR THE NEW GENERATION.',
  button_text: 'SHOP NOW',
  button_link: '/category/shirts',
  desktop_image: '',
  mobile_image: '',
  image_position: 'center',
  image_scale: 100,
  overlay_opacity: 20,
  border_radius: 0,
  bg_color: '#141210',
  text_color: '#FFFFFF',

  eyebrow: {
    enabled: true,
    text: 'POWER IN SIMPLICITY',
    fontWeight: '500',
    letterSpacing: '0.3em',
    textColor: '#FFFFFF',
    zIndex: 10,
    desktop: {
      xPosition: 8,
      yPosition: 30,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'left',
      fontSize: 14,
    },
    mobile: {
      xPosition: 8,
      yPosition: 48,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'left',
      fontSize: 12,
    },
  },

  mainHeading: {
    enabled: true,
    text: 'TIMELESS FORMALS',
    fontWeight: '400',
    letterSpacing: '0.1em',
    lineHeight: 1.1,
    maxWidth: 800,
    textColor: '#FFFFFF',
    zIndex: 11,
    desktop: {
      xPosition: 8,
      yPosition: 38,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'left',
      fontSize: 64,
      lineHeight: 1.1,
      maxWidth: 800,
    },
    mobile: {
      xPosition: 8,
      yPosition: 54,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'left',
      fontSize: 32,
      lineHeight: 1.1,
      maxWidth: 320,
    },
  },

  subDescription: {
    enabled: true,
    text: 'MODERN FITS. PREMIUM FABRICS. MADE FOR THE NEW GENERATION.',
    fontWeight: '500',
    letterSpacing: '0.2em',
    lineHeight: 1.5,
    maxWidth: 520,
    textColor: '#FFFFFF',
    zIndex: 12,
    desktop: {
      xPosition: 8,
      yPosition: 62,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'left',
      fontSize: 14,
      lineHeight: 1.5,
      maxWidth: 520,
    },
    mobile: {
      xPosition: 8,
      yPosition: 72,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'left',
      fontSize: 12,
      lineHeight: 1.4,
      maxWidth: 300,
    },
  },

  cta1: {
    enabled: true,
    text: 'SHOP NOW',
    link: '/category/shirts',
    fontWeight: '500',
    letterSpacing: '0.2em',
    textColor: '#111111',
    bgColor: '#FFFFFF',
    borderColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 0,
    buttonWidth: 'auto',
    buttonHeight: 'auto',
    zIndex: 13,
    desktop: {
      xPosition: 8,
      yPosition: 78,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'center',
      fontSize: 13,
    },
    mobile: {
      xPosition: 8,
      yPosition: 84,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'center',
      fontSize: 11,
    },
  },

  cta2: {
    enabled: false,
    text: 'EXPLORE MORE',
    link: '/about',
    fontWeight: '500',
    letterSpacing: '0.2em',
    textColor: '#FFFFFF',
    bgColor: 'transparent',
    borderColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 0,
    buttonWidth: 'auto',
    buttonHeight: 'auto',
    zIndex: 14,
    desktop: {
      xPosition: 24,
      yPosition: 78,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'center',
      fontSize: 13,
    },
    mobile: {
      xPosition: 48,
      yPosition: 84,
      alignHorizontal: 'left',
      alignVertical: 'top',
      textAlign: 'center',
      fontSize: 11,
    },
  },
};

export function normalizeHomepageHero(rawHero?: Partial<HomepageHero> | null): HomepageHero {
  if (!rawHero) return DEFAULT_HOMEPAGE_HERO;

  return {
    ...DEFAULT_HOMEPAGE_HERO,
    ...rawHero,
    eyebrow: {
      ...DEFAULT_HOMEPAGE_HERO.eyebrow!,
      ...(rawHero.eyebrow || {}),
      text: rawHero.eyebrow?.text ?? rawHero.label ?? DEFAULT_HOMEPAGE_HERO.eyebrow!.text,
      desktop: {
        ...DEFAULT_HOMEPAGE_HERO.eyebrow!.desktop,
        ...(rawHero.eyebrow?.desktop || {}),
      },
      mobile: {
        ...DEFAULT_HOMEPAGE_HERO.eyebrow!.mobile,
        ...(rawHero.eyebrow?.mobile || {}),
      },
    },
    mainHeading: {
      ...DEFAULT_HOMEPAGE_HERO.mainHeading!,
      ...(rawHero.mainHeading || {}),
      text: rawHero.mainHeading?.text ?? rawHero.heading ?? DEFAULT_HOMEPAGE_HERO.mainHeading!.text,
      desktop: {
        ...DEFAULT_HOMEPAGE_HERO.mainHeading!.desktop,
        ...(rawHero.mainHeading?.desktop || {}),
      },
      mobile: {
        ...DEFAULT_HOMEPAGE_HERO.mainHeading!.mobile,
        ...(rawHero.mainHeading?.mobile || {}),
      },
    },
    subDescription: {
      ...DEFAULT_HOMEPAGE_HERO.subDescription!,
      ...(rawHero.subDescription || {}),
      text: rawHero.subDescription?.text ?? rawHero.description ?? DEFAULT_HOMEPAGE_HERO.subDescription!.text,
      desktop: {
        ...DEFAULT_HOMEPAGE_HERO.subDescription!.desktop,
        ...(rawHero.subDescription?.desktop || {}),
      },
      mobile: {
        ...DEFAULT_HOMEPAGE_HERO.subDescription!.mobile,
        ...(rawHero.subDescription?.mobile || {}),
      },
    },
    cta1: {
      ...DEFAULT_HOMEPAGE_HERO.cta1!,
      ...(rawHero.cta1 || {}),
      text: rawHero.cta1?.text ?? rawHero.button_text ?? DEFAULT_HOMEPAGE_HERO.cta1!.text,
      link: rawHero.cta1?.link ?? rawHero.button_link ?? DEFAULT_HOMEPAGE_HERO.cta1!.link,
      desktop: {
        ...DEFAULT_HOMEPAGE_HERO.cta1!.desktop,
        ...(rawHero.cta1?.desktop || {}),
      },
      mobile: {
        ...DEFAULT_HOMEPAGE_HERO.cta1!.mobile,
        ...(rawHero.cta1?.mobile || {}),
      },
    },
    cta2: {
      ...DEFAULT_HOMEPAGE_HERO.cta2!,
      ...(rawHero.cta2 || {}),
      desktop: {
        ...DEFAULT_HOMEPAGE_HERO.cta2!.desktop,
        ...(rawHero.cta2?.desktop || {}),
      },
      mobile: {
        ...DEFAULT_HOMEPAGE_HERO.cta2!.mobile,
        ...(rawHero.cta2?.mobile || {}),
      },
    },
  };
}

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSection[] = [
  {
    id: 'hero',
    label: 'Hero',
    enabled: true,
    order: 0,
    title: 'Timeless Formals',
    subtitle: 'Power In Simplicity',
    description: 'Modern fits. Premium fabrics. Made for the new generation.',
    bg_color: '#141210',
    text_color: '#FFFFFF',
    button_text: 'Shop Now',
    button_link: '/category/shirts',
  },
  {
    id: 'shop_by_style',
    label: 'Shop By Style',
    enabled: true,
    order: 1,
    title: 'Discover The Collection',
    subtitle: 'Shop By Style',
    description: "Complete formal wear for the modern man, organised the way you shop.",
    bg_color: '#FFFFFF',
    text_color: '#141210',
    button_text: 'Explore',
    button_link: '/category/shirts',
  },
  {
    id: 'new_arrivals',
    label: 'New Arrivals',
    enabled: true,
    order: 2,
    title: 'New Arrivals',
    subtitle: 'Just Landed',
    description: 'Fresh styles. Premium quality. Be the first to explore this season\u2019s edit.',
    bg_color: '#F4F2EC',
    text_color: '#141210',
    button_text: 'Shop New In',
    button_link: '/category/shirts',
  },
  {
    id: 'featured_collection',
    label: 'Featured Collection',
    enabled: true,
    order: 3,
    title: 'Best Sellers',
    subtitle: 'Featured Collection',
    description: 'The pieces our clients reach for first — tailored, tested, and true to size.',
    bg_color: '#FFFFFF',
    text_color: '#141210',
    button_text: 'Shop Best Sellers',
    button_link: '/category/shirts',
  },
  {
    id: 'premium_fabrics',
    label: 'Premium Fabrics',
    enabled: true,
    order: 4,
    title: 'Premium Fabrics',
    subtitle: 'Built To Move',
    description: 'Brushed twill, silk-cotton blends and breathable weaves, sourced for a twelve-hour day.',
    bg_color: '#141210',
    text_color: '#FFFFFF',
    button_text: 'Learn More',
    button_link: '/about',
    images: [],
  },
  {
    id: 'why_dvero',
    label: 'Why D\u2019VERO',
    enabled: true,
    order: 5,
    title: 'Why D\u2019VERO',
    subtitle: 'The Difference',
    description: 'Precision tailoring, honest pricing and formalwear that is true to how you actually stand in a room.',
    bg_color: '#FFFFFF',
    text_color: '#141210',
    button_text: 'Read Our Story',
    button_link: '/about',
  },
  {
    id: 'reviews',
    label: 'Reviews',
    enabled: true,
    order: 6,
    title: 'Loved By Our Clients',
    subtitle: 'Reviews',
    description: 'Real feedback from the people wearing D\u2019VERO every day.',
    bg_color: '#F4F2EC',
    text_color: '#141210',
    button_text: '',
    button_link: '',
  },
  {
    id: 'instagram',
    label: 'Instagram',
    enabled: true,
    order: 7,
    title: 'Follow @dvero.in',
    subtitle: 'Instagram',
    description: 'Tag us in your D\u2019VERO fits for a chance to be featured.',
    bg_color: '#FFFFFF',
    text_color: '#141210',
    button_text: 'Follow Us',
    button_link: 'https://instagram.com/dvero.in',
    images: [],
  },
  {
    id: 'newsletter',
    label: 'Newsletter',
    enabled: true,
    order: 8,
    title: 'Join The List',
    subtitle: 'Newsletter',
    description: 'Be first to hear about new drops, restocks and studio events.',
    bg_color: '#141210',
    text_color: '#FFFFFF',
    button_text: 'Subscribe',
    button_link: '',
  },
];

export const DEFAULT_HOMEPAGE_THEME: HomepageTheme = {
  bg_color: '#FFFFFF',
  primary_color: '#141210',
  secondary_color: '#8A8175',
  accent_color: '#A8987C',
  button_style: 'sharp',
  border_radius: 4,
  shadow: 'soft',
  container_width: 1360,
};

export const DEFAULT_PROMO_BANNERS: PromoBanners = {
  mens_collection: {
    enabled: true,
    desktop_image: '',
    mobile_image: '',
    title: "Men's Collection",
    subtitle: '',
    description: 'Complete formal wear for the modern man.',
    button_text: 'Explore',
    button_link: '/category/shirts',
    text_position: 'left',
    vertical_position: 'bottom',
    text_color: '#FFFFFF',
    overlay_color: '#141210',
    overlay_opacity: 70,
    gradient_enabled: true,
  },
  shirts: {
    enabled: true,
    desktop_image: '',
    mobile_image: '',
    title: 'Shirts',
    subtitle: '',
    description: 'Crisp. Refined. Effortlessly stylish.',
    button_text: 'Explore',
    button_link: '/category/shirts',
    text_position: 'left',
    vertical_position: 'bottom',
    text_color: '#141210',
    overlay_color: '#F4F2EC',
    overlay_opacity: 55,
    gradient_enabled: true,
  },
  trousers: {
    enabled: true,
    desktop_image: '',
    mobile_image: '',
    title: 'Trousers',
    subtitle: '',
    description: 'Tailored to perfection. Made to move with you.',
    button_text: 'Explore',
    button_link: '/category/trousers',
    text_position: 'left',
    vertical_position: 'bottom',
    text_color: '#141210',
    overlay_color: '#F4F2EC',
    overlay_opacity: 55,
    gradient_enabled: true,
  },
  new_arrivals: {
    enabled: true,
    desktop_image: '',
    mobile_image: '',
    title: 'New Arrivals',
    subtitle: 'New In',
    description: 'Fresh styles. Premium quality. Be the first to explore.',
    button_text: 'Shop Now',
    button_link: '#drop01',
    text_position: 'left',
    vertical_position: 'center',
    text_color: '#141210',
    overlay_color: '#F4F2EC',
    overlay_opacity: 45,
    gradient_enabled: true,
  },
};
