import { HomepageHero, HomepageSection, HomepageTheme, PromoBanners } from './types';

export const DEFAULT_HOMEPAGE_HERO: HomepageHero = {
  enabled: true,
  layout: 'split',
  label: 'Power In Simplicity',
  heading: 'Timeless Formals',
  description: 'Modern fits. Premium fabrics. Made for the new generation.',
  button_text: 'Shop Now',
  button_link: '/category/shirts',
  desktop_image: '',
  mobile_image: '',
  image_position: 'center',
  image_scale: 100,
  overlay_opacity: 0,
  border_radius: 0,
  bg_color: '#141210',
  text_color: '#FFFFFF',
};

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSection[] = [
  {
    id: 'hero',
    label: 'Hero',
    enabled: true,
    order: 0,
    title: 'Timeless Formals',
    subtitle: 'Power In Simplicity',
    description: 'Modern fits. Premium fabrics. Made for the new generation.',
    bg_color: '#141210',
    text_color: '#FFFFFF',
    button_text: 'Shop Now',
    button_link: '/category/shirts',
  },
  {
    id: 'shop_by_style',
    label: 'Shop By Style',
    enabled: true,
    order: 1,
    title: 'Discover The Collection',
    subtitle: 'Shop By Style',
    description: "Complete formal wear for the modern man, organised the way you shop.",
    bg_color: '#FFFFFF',
    text_color: '#141210',
    button_text: 'Explore',
    button_link: '/category/shirts',
  },
  {
    id: 'new_arrivals',
    label: 'New Arrivals',
    enabled: true,
    order: 2,
    title: 'New Arrivals',
    subtitle: 'Just Landed',
    description: 'Fresh styles. Premium quality. Be the first to explore this season\u2019s edit.',
    bg_color: '#F4F2EC',
    text_color: '#141210',
    button_text: 'Shop New In',
    button_link: '/category/shirts',
  },
  {
    id: 'featured_collection',
    label: 'Featured Collection',
    enabled: true,
    order: 3,
    title: 'Best Sellers',
    subtitle: 'Featured Collection',
    description: 'The pieces our clients reach for first — tailored, tested, and true to size.',
    bg_color: '#FFFFFF',
    text_color: '#141210',
    button_text: 'Shop Best Sellers',
    button_link: '/category/shirts',
  },
  {
    id: 'premium_fabrics',
    label: 'Premium Fabrics',
    enabled: true,
    order: 4,
    title: 'Premium Fabrics',
    subtitle: 'Built To Move',
    description: 'Brushed twill, silk-cotton blends and breathable weaves, sourced for a twelve-hour day.',
    bg_color: '#141210',
    text_color: '#FFFFFF',
    button_text: 'Learn More',
    button_link: '/about',
    images: [],
  },
  {
    id: 'why_dvero',
    label: 'Why D\u2019VERO',
    enabled: true,
    order: 5,
    title: 'Why D\u2019VERO',
    subtitle: 'The Difference',
    description: 'Precision tailoring, honest pricing and formalwear that is true to how you actually stand in a room.',
    bg_color: '#FFFFFF',
    text_color: '#141210',
    button_text: 'Read Our Story',
    button_link: '/about',
  },
  {
    id: 'reviews',
    label: 'Reviews',
    enabled: true,
    order: 6,
    title: 'Loved By Our Clients',
    subtitle: 'Reviews',
    description: 'Real feedback from the people wearing D\u2019VERO every day.',
    bg_color: '#F4F2EC',
    text_color: '#141210',
    button_text: '',
    button_link: '',
  },
  {
    id: 'instagram',
    label: 'Instagram',
    enabled: true,
    order: 7,
    title: 'Follow @dvero.in',
    subtitle: 'Instagram',
    description: 'Tag us in your D\u2019VERO fits for a chance to be featured.',
    bg_color: '#FFFFFF',
    text_color: '#141210',
    button_text: 'Follow Us',
    button_link: 'https://instagram.com/dvero.in',
    images: [],
  },
  {
    id: 'newsletter',
    label: 'Newsletter',
    enabled: true,
    order: 8,
    title: 'Join The List',
    subtitle: 'Newsletter',
    description: 'Be first to hear about new drops, restocks and studio events.',
    bg_color: '#141210',
    text_color: '#FFFFFF',
    button_text: 'Subscribe',
    button_link: '',
  },
];

export const DEFAULT_HOMEPAGE_THEME: HomepageTheme = {
  bg_color: '#FFFFFF',
  primary_color: '#141210',
  secondary_color: '#8A8175',
  accent_color: '#A8987C',
  button_style: 'sharp',
  border_radius: 4,
  shadow: 'soft',
  container_width: 1360,
};

export const DEFAULT_PROMO_BANNERS: PromoBanners = {
  mens_collection: {
    enabled: true,
    desktop_image: '',
    mobile_image: '',
    title: "Men's Collection",
    subtitle: '',
    description: 'Complete formal wear for the modern man.',
    button_text: 'Explore',
    button_link: '/category/shirts',
    text_position: 'left',
    vertical_position: 'bottom',
    text_color: '#FFFFFF',
    overlay_color: '#141210',
    overlay_opacity: 70,
    gradient_enabled: true,
  },
  shirts: {
    enabled: true,
    desktop_image: '',
    mobile_image: '',
    title: 'Shirts',
    subtitle: '',
    description: 'Crisp. Refined. Effortlessly stylish.',
    button_text: 'Explore',
    button_link: '/category/shirts',
    text_position: 'left',
    vertical_position: 'bottom',
    text_color: '#141210',
    overlay_color: '#F4F2EC',
    overlay_opacity: 55,
    gradient_enabled: true,
  },
  trousers: {
    enabled: true,
    desktop_image: '',
    mobile_image: '',
    title: 'Trousers',
    subtitle: '',
    description: 'Tailored to perfection. Made to move with you.',
    button_text: 'Explore',
    button_link: '/category/trousers',
    text_position: 'left',
    vertical_position: 'bottom',
    text_color: '#141210',
    overlay_color: '#F4F2EC',
    overlay_opacity: 55,
    gradient_enabled: true,
  },
  new_arrivals: {
    enabled: true,
    desktop_image: '',
    mobile_image: '',
    title: 'New Arrivals',
    subtitle: 'New In',
    description: 'Fresh styles. Premium quality. Be the first to explore.',
    button_text: 'Shop Now',
    button_link: '#drop01',
    text_position: 'left',
    vertical_position: 'center',
    text_color: '#141210',
    overlay_color: '#F4F2EC',
    overlay_opacity: 45,
    gradient_enabled: true,
  },
};
